[package]
name = "pw_unified_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.3.0"

lexan = { git = "https://github.com/pwil3058/rs_lalr1_parsers" }
lalr1 = { git = "https://github.com/pwil3058/rs_lalr1_parsers" }
