[package]
name = "pw_patch"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
stderrlog = "0.6.0"
temp-file = "0.1"

longest_common_subsequence = { path = "../longest_common_subsequence" }
pw_diff_lib = { path = "../pw_diff_lib" }
