[package]
name = "diff_lib_ng"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.200", features = ["derive"] }
rayon = "1.10.0"
log = "0.4"
serde_json = "1.0.116"
